version: '3.7'
services:
  postgres:
    restart: always
    image: postgres:9
    environment:
      - POSTGRES_USER=dawidbodych
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=websearch_app

    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["python3", "main.py"]
